### ISSUE TITLE
No documentation for connection_name parameter

### ISSUE THREAD

**Issue by strokirk** [rabbitmq/rabbitmq-website#1111]
The `connection_name` parameter to client-properties allows you to set a human-readable connection name to be displayed in the RabbitMQ admin interface:

![Screenshot 2020-12-11 at 18 27 50](https://user-images.githubusercontent.com/1257824/102324553-4ae8c800-3f82-11eb-9d5d-a13e13815a2a.png)

However, the only place this is mention is in the release notes for 3.6.2, making it hard to search for:
https://github.com/rabbitmq/rabbitmq-server/issues/104

**Comment by michaelklishin** [comment]
This is [not true](https://www.rabbitmq.com/api-guide.html#client-provided-names).

**Comment by michaelklishin** [comment]
It's not obvious where it would be most discoverable since users of different languages and libraries will look at different tutorials, doc guides and so on. I will add it to the general Connections guide but it's rarely the place of choice for beginners.

API references of several clients mention various functions. Perhaps certain sections of the logging guide can link to it as well because this value will also be used in the [connection lifecycle log messages](https://www.rabbitmq.com/logging.html#logged-events), if set.

**Comment by strokirk** [comment]
Thanks a lot @michaelklishin! 

I did not find that section even after a long time searching online and in this repo, probably because it doesn't mention the string `connection_name` explicitly. But now I know, and can search for this Github issue in the future (when I invariably forget)!

**Comment by michaelklishin** [comment]
This feature is called "user-provided connection name" by our team. In order to search for `"connection_name"` you must know about it already one way or another.

**Comment by strokirk** [comment]
Yes, I heard about it one way or the other, but what was difficult was knowing exactly what parameter name to forward into RabbitMQ from our client library (we use py-amqp, which just surfaces a "`client_properties`" parameter that I guess gets sent into RabbitMQ mostly unaltered).

**Comment by michaelklishin** [comment]
Perhaps someone could contribute a more prominent way of setting it for a connection to `py-amqp` :)
