### ISSUE TITLE
Broken Documentation Link

### ISSUE THREAD

**Issue by CorvusVeis** [rabbitmq/rabbitmq-website#1170]
This link stopped working today. It worked yesterday. It now sends the user to Page Not Found.

https://www.rabbitmq.com/releases/rabbitmq-dotnet-client/v3.6.4/rabbitmq-dotnet-client-3.6.4-client-htmldoc/html/type-RabbitMQ.Client.IModel.html#method-M:RabbitMQ.Client.IModel.MessageCount(System.String)

**Comment by michaelklishin** [comment]
@CorvusVeis I'm sorry but I'm going to challenge your claim that it had stopped working yesterday. `rabbitmq.com/releases` has not been updated since 2016 or so, and completely gone around February this year when the site moved to CloudFlare Workers and thus no longer uses the VM with the original file archives.

We have had an older release archive on Bintray. However, Bintray itself shuts down on May 1st. You can provision RabbitMQ .NET client 3.6.9 from [nuget.org](https://www.nuget.org/packages/RabbitMQ.Client/). I don't see why anyone would use such an old version but if you have to, at least use `3.6.9`. It should support the same .NET versions as `3.6.4`. However, consider upgrading, you are three (and fairly soon will be four) major versions behind.

**Comment by michaelklishin** [comment]
As for the docs, the [doc guide](https://www.rabbitmq.com/dotnet-api-guide.html) has not moved anywhere in over a decade and [.NET client API reference](https://rabbitmq.github.io/rabbitmq-dotnet-client/index.html) has been available from GitHub for over a year IIRC. It does not cover 3.6 but many API elements are still the same.
