### ISSUE TITLE
Improve "Installing on Debian and Ubuntu" documentation

### ISSUE THREAD

**Issue by manueljordan** [rabbitmq/rabbitmq-website#1174]
Hello I want install RabbitMQ - it on Ubuntu Desktop 18.04 and 20.04
I arrived to this page:

* [Installing on Debian and Ubuntu](https://www.rabbitmq.com/install-debian.html)

**Note**: I am writing this post with the best intentions (respecting your work) and being polite

About repositories I understood there are 2 repositories to select, it either _launchpad_ or _Cloudsmith.io_, but just one to choice
According with the suggestion (and I am agree) I choose:

* [Install Erlang from an Apt Repository (PPA) on Launchpad](https://www.rabbitmq.com/install-debian.html#apt-launchpad-erlang)

In the _Add Repository Signing Key_ subsection appears two ways:

* _This can be done using a **key server** or via **direct key download**_

In the _Add a Source List File_ subsection appears `$distribution`, **One**: I think should be indicated _explicitly_ that that value must be replaced with some value available in the `Distribution` subsection **and** change it to `{distribution}`, in that way is used later (the point is avoid confusions)

About the _Debian Package Version and Repository Pinning_ subsection is not clear if is mandatory to be applied without matter what approach was used (_launchpad_ or _Cloudsmith.io_) - so - **two** - it should be indicated if that section is mandatory or not.

In the same section appears:

```
# /etc/apt/preferences.d/erlang
Package: erlang*
Pin: origin ppa.launchpad.net
Pin-Priority: 1000
```

I am assuming that setting is mandatory, right? (Same for the  _Cloudsmith.io_ version) - **Three** indicate that _explicitly_. 

In the same section there is the following sentence _The following preference file example will pin all erlang-* packages to 23.3 (assuming package epoch for the package is 1):_ - So **four** indicate _explicitly_ if the 3 snippet codes after of that sentence are optional or not.

In the _Quick Start Example_ sub-section should be added the other version for the _direct key download_ approach too. The current approach is based only in _key server_

There are more observations, but to avoid more verbose comment, I friendly suggest: 

Post the complete instructions for each approach: I mean

* _Launchpad_ with via _**direct key download**_
* _Launchpad_ with _**key server**_
* _Cloudsmith.io_ with via _**direct key download**_
* _Cloudsmith.io_ with _**key server**_

Otherwise the current _Quick Start Example_ section is confuse, because there is only 1 approach covered, among the many approaches available, even worst, because seems there are optional configurations that are not indicated explicitly.

**Problem:** I am not able to follow quick and easily the installation instructions how I am able to follow for Postgresql and MongoDB for example.

Thanks for your understanding

**Comment by michaelklishin** [comment]
Thank you for your feedback. I will edit a few things but it does not seem practical for us to list 4 different extensive instruction sets. Having two for two repositories already makes the guide harder to maintain and navigate unless you pick one option right from the ToC.

The only reason why we list two ways of importing signing keys is that key servers are generally not known for stability
but a lot of Debian users prefer this over manual file downloads.

We cannot replace `$distribution` with an explicit value because we don't know what distribution you use. Both PackageCloud and Cloudsmith provide single line installation scripts which we do mention. They infer the
distribution and set up a repository file for you. Our instructions are provide for those who want to understand
what is involved and do not feel comfortable piping the Internet to a sudo shell.

I don't know if `{distribution}` would be clearer than `$distribution` as the latter is used by some of Debian and Ubuntu guides.

**Comment by michaelklishin** [comment]
[MongoDB Debian installation guide](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/) marks one optional step and uses three panes for three supported distributions. They also separate Debian from Ubuntu
and do not mention any prerequisites the guide relies on, e.g. `wget`.

Assuming that [this is the PostgreSQL guide you are comparing to](https://www.postgresql.org/download/linux/debian/),
it basically provides a script you can follow.

Our guide can make it clear what steps (e.g. version pinning) is optional. It already does provide two quick options:

 * A single line "Internet-to-sudo-shell" option (which is not for everyone)
 * A quick start script that you can copy and paste

In addition, we cover more topics (e.g. Erlang installation, version pinning) and list two package repositories because
we believe a single repository makes us too dependent on one external service. Our guide seems adequate
given that it is somewhat different in scope.

We will make optional steps as such and consider dropping the key server option (it is already covered in the [Package Signatures guide](https://www.rabbitmq.com/signatures.html)). Thank you for the suggestions.

**Comment by michaelklishin** [comment]
I have updated the guide to focus on installation of both RabbitMQ and Erlang from either

 * Cloudsmith (which actually provides both)
 * A combination of Launchpad and PackageCloud

Both options now have Quick Start scripts and simplified individual step sections. We no longer mention key servers
explicitly but various scripts use them where it's more convenient.

Without certain UI changes we can't provide the same multi-pane instructions per distribution but we do provide
more explicit examples now. `{distribution}` has been dropped in favor of `$distribution` in the generalized example.

HTH.

**Comment by manueljordan** [comment]
Hello Michael

About `$distribution` my point was change to `{distribution}` - it to keep the whole document with the same pattern (perhaps `<distribution>` or `[distribution]`). Consider to indicate explicitly that currently that either `$distribution` or `{distribution}` must be replaced with the correct _distribution_ value (bionic or focal) - understood that  `$distribution` was chosen

My comparison with the other guides is that they are based on few and quick instructions to install them, that's all. Ironically Install RabbitMQ (and Erlang) on Windows is easier than Ubuntu. BTW I never said that the current Linux installation guide is neither bad nor poor. It is confuse in some way, and is long. Yes I know that Erlang is mandatory too.

Thanks for the quick update of the guide. I am going to try it again. 

p.d: Like I wrote in the beginning - I wrote the post with the best intentions (respecting your work) and being polite
