### ISSUE TITLE
List supported `ack_mode` parameter values in static shovel documentation

### ISSUE THREAD

**Issue by mikhailantoshkin** [rabbitmq/rabbitmq-website#2013]
### Is your feature request related to a problem? Please describe.

Documentation of static shovel configuration never explicitly names variants of `ack_mode` that can be used in configuration. Instead, it refers to them in three different ways. As [confirm](https://github.com/rabbitmq/rabbitmq-website/blob/c3261157d8d13ac45b83ac6bbfc927cd3c2aaa95/docs/shovel-static.md?plain=1#L77) being default, [on-confirm](https://github.com/rabbitmq/rabbitmq-website/blob/c3261157d8d13ac45b83ac6bbfc927cd3c2aaa95/docs/shovel-static.md?plain=1#L157) and [on_confirm](https://github.com/rabbitmq/rabbitmq-website/blob/c3261157d8d13ac45b83ac6bbfc927cd3c2aaa95/docs/shovel-static.md?plain=1#L674) being the only correct option.

When using an incorrect variant the error message lists available options as  `no_ack`, `on_publish` and `on_confirm`.

### Describe the solution you'd like

Refer to variants of `ack_mode` in a consistent way and explicitly list available variants, probably in [this block](https://github.com/rabbitmq/rabbitmq-website/blob/c3261157d8d13ac45b83ac6bbfc927cd3c2aaa95/docs/shovel-static.md?plain=1#L153-L173)

**Comment by michaelklishin** [comment]
@mikhailantoshkin the very section you have linked to does mention all three. You can set the value to `confirm` even though it is the default.

I don't know what exactly "a consistent way" means to you but the parameter reference seems perfectly complete to me. I will mention all three options explicitly.

In the future, consider submitting a pull request instead of asking for a change in such generic terms.
