### ISSUE TITLE
Re-order .NET dev tools

### ISSUE THREAD

**Issue by adamralph** [rabbitmq/rabbitmq-website#422]
On the [dev tools page](https://www.rabbitmq.com/devtools.html), how is the order of the lists determined?

Specifically, I'm wondering how the order of the [.NET tools](https://github.com/rabbitmq/rabbitmq-website/blob/e6e34f7fe63e0350b6752306f48105e2ba753850/site/devtools.xml#L76-L93) is determined.

Currently, the order seems to be quite random. Should it be alphabetical, or should another criteria be used, such as descending order of number of NuGet downloads? Or something representing the level of activity in each project?

Full disclosure: I work for https://particular.net/, the makers of NServiceBus, and it's in our interest to adopt an ordering which puts NServiceBus nearer the top, but if you prefer not to using any "ranking" criteria then I'm equally happy to send a PR to order the tools alphabetically.

**Comment by michaelklishin** [comment]
We do not use alphabetical ordering and ordering is often either

 * By popularity (which is subjective and driven by our gut feeling but FWIW our team interacts with the users enough to not be out of touch)
 * Chronologically (new projects that are worth adding are added to the end)

Every so often the list is purged if a project is no longer actively maintained, there is a more popular alternative, etc. This is not a particularly scientific process, though.

We definitely want RabbitMQ clients we maintain to be at the top of each section. [NServiceBus is number 3 in its category](https://github.com/rabbitmq/rabbitmq-website/blob/live/site/devtools.xml). EasyNetQ has been around [since 2011](https://github.com/EasyNetQ/EasyNetQ/graphs/contributors), is maintained and is a very popular project. According to [this chart](https://github.com/Particular/NServiceBus.RabbitMQ/graphs/contributors), NServiceBus RabbitMQ transport has been around since 2014.

So this ordering seems pretty fair to me. If there is hard data that proves that NServiceBus is the second most popular after RabbitMQ .NET client, I'd consider rearranging them but honesty, I don't think it matters that much since both are visibly listed and have fairly different scopes.

**Comment by adamralph** [comment]
@michaelklishin thanks the response. That seems reasonable.

> Every so often the list is purged of projects that are no longer actively maintained, have a more popular alternative, etc.

FWIW, it seem like [RestBus](https://github.com/tenor/RestBus) may have been abandoned.
