### ISSUE TITLE
Bad Link (404) in https://www.rabbitmq.com/confirms.html

### ISSUE THREAD

**Issue by garyrussell** [rabbitmq/rabbitmq-website#509]
>An example in Java that publishes a large number of messages to a channel in confirm mode and waits for the acknowledgements can be found [here](https://raw.githubusercontent.com/rabbitmq/rabbitmq-perf-test/master/src/main/java/com/rabbitmq/examples/ConfirmDontLoseMessages.java).

**Comment by michaelklishin** [comment]
Hi @garyrussell. We've [removed](https://github.com/rabbitmq/rabbitmq-perf-test/commit/6217d3b415fed9904a7b07a303f45662e16671cb) those examples from PerfTest because they don't really belong in any of the repos we have and some are no longer relevant.

Specifically the example in question isn't even going to compile with the Java client 5.x. Do you think it'd be worth having the example or should we just remove any mentions from the docs?

**Comment by michaelklishin** [comment]
Yeah, and using `Channel#waitForConfirmsOrDie` isn't necessarily example-worthy. Streaming confirms is a different story.

**Comment by garyrussell** [comment]
Hi @michaelklishin I don't really have an opinion either way 😄, removing it is fine with me; I was just pointing out the bad link.
