### ISSUE TITLE
Do a code review for OpenStack Oslo RabbitMQ adapter

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-website#6]
and suggest possible points of improvement.

Filing here for the lack of a more suitable place. We want a list of specific points of improvements in the end as the outcome of this.

**Comment by dims** [comment]
@yosh @michaelklishin - Is this enough? https://review.openstack.org/#/c/185989/ for publisher confirm?

**Comment by sileht** [comment]
@yosh @michaelklishin: The locks mechanism we have in the oslo.messaging driver is not only for protecting the usage of the connection by two threads but especialy because eventlet doesn't allow us to share a file descriptor between threads (greenthreads).

**Comment by michaelklishin** [comment]
@sileht thanks for clarifying. @dims we will take a look later this or early next week. Thanks, guys!

**Comment by yosh** [comment]
Just turning that option on in the lower level driver would be fairly suboptimal performance, since it'll now block for the message to be consumed on all queues, or persisted to disk before returning: https://github.com/celery/py-amqp/blob/master/amqp/channel.py#L1749

Since the default is non-durable queues, this may block the publisher from proceeding if the consumer(s) are busy. For RPC this wouldn't really be a big deal in the call case, but would in the cast case. This definitely would be bad for the notification case.

The right thing here is to save some state in the async case, and check periodically if the messages have actually been queued up, and redeliver if not. I've got some code myself that does this, but it's incomplete so far.

**Comment by michaelklishin** [comment]
Not disagreeing with the suggestion but I'd like to clarify that publisher confirms are unaware of consumers. See [When Will Messages Be Confirmed](http://www.rabbitmq.com/confirms.html). Internal flow control in theory may affect confirm delivery latency but it won't be a problem in practice.

**Comment by yosh** [comment]
Ah yes indeed, it's confirming that it got somewhere internally in rabbit, independent of consumers.

So upon trying to flesh out my async check code, the approaches I tried turned out to be less performant than what that little patch did, so it's probably good enough for now. The Basic.nack case isn't handled, but that should be rare (@michaelklishin correct me if I've made a wrong assumption here), and in case of a timeout during the wait, the autoretry code should take care of redelivery..

Switching over to pika would help here, but that's a larger discussion.

**Comment by dims** [comment]
@yosh Can you please point me to specific features/implementation in Pika that are not present in kombu+pyamqp that would help oslo.messaging?

**Comment by michaelklishin** [comment]
`basic.nack` from the broker is rare and the easiest way to trigger it is to cause queue [Erlang] process to crash with some `rabbitmqctl eval` magic.

**Comment by michaelklishin** [comment]
@dims I'll let @yosh name specific technical differences since he's been looking into recent Pika versions but there's one major reason for me to recommend Pika: it is a library that is maintained.

**Comment by michaelklishin** [comment]
@yosh re-assigned to you. Feel free to close this when you feel we're done with the evaluation and identifying specific points of improvement.

**Comment by yosh** [comment]
@dims Pika has a few things going for it:

* async API from the get go. Would help with the confirms code, since the confirm ack/nack could be processed in an event driven fashion instead of the request/response latency here.
* it's simpler than kombu. oslo_messaging doesn't need/want most of the higher level features that kombu has.
* pika has it's own heartbeat code, which spreads out the maintenance cost of that feature
* pika also seems to track rabbitmq features better (e.g. the basic.nack mentioned above)

**Comment by dims** [comment]
@yosh @michaelklishin - interesting. So the very first scenario we would need as a prototype using pika would be to get the simulator working (https://github.com/openstack/oslo.messaging/blob/master/tools/simulator.py) with the rpc-client/rpc-server and notify-client/notify-server scenarios.

**Comment by billbr** [comment]
A lurker's comment: Be aware that pika is not thread or multiprocess safe in its current state.

**Comment by michaelklishin** [comment]
@billbr what specifically isn't thread-safe? Most clients don't support sharing channels between threads by design. Connections can be shared, however.

**Comment by billbr** [comment]
We have some complex internal QA tools that use RabbitMQ. We have found that connection sharing does cause issues. The connection object carries a lot of state information that can be mostly protected by using a lock with rabbit transactions but still gets socket timeouts that cause pika to throw an exception for connection open on a closed socket. Our application currently opens a connection per process and per thread. We weren’t expecting channel sharing.  Our team is all fairly new to RabbitMQ and have learned quite a lot in the last 5 months of use but acknowledge that we might be “doing it wrong”.  We publish using BlockingConnections and consume via SelectConnections.

Since OpenStack is using Kombu, we were even considering changing our interface library.

Bill Brothers
HP

**Comment by billbr** [comment]
@dims, @yosh, I though I would just add that the heartbeat code in pika works really well unless you block the execution of the thread that pika is running on. So any OS blocking code (read, wait, etc.) will cause the connection to close with a hearbeat timeout after 2 * the heartbeat interval.

**Comment by dims** [comment]
@billbr Are you thinking pika with kombu or directly using pika? (with oslo.messaging)

**Comment by michaelklishin** [comment]
Heartbeat interval is rarely below 10 seconds (almost 5 minutes by default). It will take a really long read or write. Several other clients do I/O and send heartbeats concurrently.

I'd recommend not dragging Kombu along. oslo.messaging should use client libraries for data services directly, not via wrappers.

**Comment by billbr** [comment]
@dims, we are just "looking at" kombu potential as a pika replacement. Our app is stand-alone python app. At some point we may migrate it to a cloud-based app.

**Comment by billbr** [comment]
@michaelklishin Agreed. However our rpc design found that issue quickly as we were dispatching long-running work tasks and waiting for the results. The tasks used pipes to communicate and collect information. :-(  So now we thread off the task and collect the results in a more async manner.

**Comment by dukhlov** [comment]
Hello guys! I just started implementation of pika driver for oslo messaging and have a couple of questions. We have two types of communications - messages listening and publishing. I plan to use Blocking conections because we have our own executors mechanism. For listening we need long term connection, it could be closed because of losing connectivity, staling or something else, so we also need some manually implemented recovery mechanism. For publishing we need short term connection just for publishing. The question is: Is it possible to use single connection for whole driver and create new channel for each publish request or probably create pool of channels and/or connections? Is it good practice to use long live connections/channels? Another words what are the best practices for organizing connections to RabbitMQ? BTW, I haven't found possibility in pika to connect to rabbitmq cluster (specify set of hosts), so I am going to implement custom ConnectionFactory and use round robin defined host for creating new connection. Is it it ok? Probably Pika has already something ready to use for this purpose?

**Comment by michaelklishin** [comment]
Dmitriy,

Thank you for looking into this. I suggest moving this discussion to rabbitmq-users so that Pika maintainers can participate.

**Comment by dims** [comment]
@yosh @michaelklishin - Need your feedback/code review on a pika based oslo.messaging driver. details are here - http://markmail.org/message/wvlel7opbsxbcj4b

**Comment by yosh** [comment]
Awesome! Will take a look in the next couple days.

**Comment by michaelklishin** [comment]
@yosh thank you!
