### ISSUE TITLE
gen_server2 buffer overflow on redelivery 

### ISSUE THREAD

**Issue by scor2k** [rabbitmq/rabbitmq-website#691]
Hello.

We have issue with huge gen_server2 buffer when some queue with continuously ( ~20 min ) redelivery. In this case gen_server2 buffer grow up to 10k and more. While it grow up our other queues working worse. 

We can fix it only by dropping this queue or restart node with this queue, but we don't like to do this, because we are losing some information. 
 
P.S. We are using top_process plugin to monitoring gen_server2 buffer value. 

Additional information: 

rabbitmq-server: 3.7.3-1

![getimage](https://user-images.githubusercontent.com/6481670/53158011-bb676d80-35d3-11e9-954b-592b1b6eb207.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
`gen_server2` buffer is a queue of pending process operations, be it routed message handling or something else. Just like Erlang mailbox, it is unbounded. If it grows larger and larger, the queue cannot keep up with the rate of operations. Very likely that you are looking at the [Single Giant Queue antipattern](http://www.rabbitmq.com/queues.html#runtime-characteristics), not much else.
