### ISSUE TITLE
have a issue on Dead Letter Exchanges

### ISSUE THREAD

**Issue by xiaowuyz** [rabbitmq/rabbitmq-website#706]
i config:   
 channel.exchange_declare('some.exchange.name', 'direct')
    args = {"x-dead-letter-exchange": "some.exchange.name", 'x-dead-letter-routing-key': 'exchange'}
    channel.queue_declare("test3", durable=True, arguments=args)

but 
![TIM截图20190314180304](https://user-images.githubusercontent.com/31556062/54348147-6f17c680-4683-11e9-9121-5d994d80fc62.png)

I don't know why

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Having a DLX argument won't set up any bindings. Those parameters will only be used at dead lettering time to republish the dead lettered messages. DLX does not affect how routing works for "regular" publishing scenarios.
