### ISSUE TITLE
error for use this command

### ISSUE THREAD

**Issue by gxlqssjf** [rabbitmq/rabbitmq-website#741]
C:\Program Files\RabbitMQ Server\rabbitmq_server-3.7.14\sbin>rabbitmq-plugins enable rabbitmq_management
文件名、目录名或卷标语法不正确。
文件名、目录名或卷标语法不正确。
EnumerateProviders catalog=0
EnumerateProviders totalPro=26
** (MatchError) no match of right hand side value: {:error, {:node_name, :hostname_not_allowed}}
    (rabbitmqctl) lib/rabbitmq/cli/core/helpers.ex:32: RabbitMQ.CLI.Core.Helpers.normalise_node/2
    (rabbitmqctl) lib/rabbitmqctl.ex:232: RabbitMQCtl.merge_defaults_node/1
    (rabbitmqctl) lib/rabbitmqctl.ex:225: RabbitMQCtl.merge_all_defaults/1
    (rabbitmqctl) lib/rabbitmqctl.ex:103: RabbitMQCtl.exec_command/2
    (rabbitmqctl) lib/rabbitmqctl.ex:45: RabbitMQCtl.main/1
    (elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2

use 127.0.0.1:5672 in QQbrowser :
![image](https://user-images.githubusercontent.com/1277598/56417115-7acf5c00-62c5-11e9-987d-a9aec65f73b5.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Something about the hostname you are trying this on is not right. The runtime has certain limitations as to what characters hostnames are allowed to have and RabbitMQ cannot do anything about it. Please start a mailing list thread and specify what `hostname` and `hostname -f` returns on that machine.

**Comment by michaelklishin** [comment]
Alternatively a list of plugins can be [preconfigured without using CLI tools](https://www.rabbitmq.com/plugins.html#enabled-plugins-file) but you probably will need CLI tools at some point.
