### ISSUE TITLE
Instructions to install erlang wrong for Ubuntu 18.04 bionic

### ISSUE THREAD

**Issue by digulla** [rabbitmq/rabbitmq-website#763]
When I follow the instructions on https://www.rabbitmq.com/install-debian.html#apt-bintray-erlang, I add this file to apt:

```
# Installs the latest 21.x version available in the repository.
deb http://dl.bintray.com/rabbitmq-erlang/debian bionic erlang-21.x
```

then `apt-get update` will print:

```
Reading package lists... Done
W: Skipping acquire of configured file 'erlang-20.x/i18n/Translation-en_US' as repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' doesn't have the component 'erlang-20.x' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'erlang-20.x/i18n/Translation-en' as repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' doesn't have the component 'erlang-20.x' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'erlang-20.x/dep11/Components-amd64.yml' as repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' doesn't have the component 'erlang-20.x' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'erlang-20.x/dep11/icons-48x48.tar' as repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' doesn't have the component 'erlang-20.x' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'erlang-20.x/dep11/icons-64x64.tar' as repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' doesn't have the component 'erlang-20.x' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'erlang-20.x/Contents-amd64' as repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' doesn't have the component 'erlang-20.x' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'erlang-20.x/Contents-i386' as repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' doesn't have the component 'erlang-20.x' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'erlang-20.x/cnf/Commands-amd64' as repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' doesn't have the component 'erlang-20.x' (component misspelt in sources.list?)
```

It works with this entry in the sources.list:

    deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang

(i.e. omit the "-20.x").

Unfortunately, this gives me Erlang 22 and installing rabbitmq-server fails with:

```
 rabbitmq-server : Depends: erlang-base (< 1:22) but 1:22.0-1 is to be installed or
                            erlang-base-hipe (< 1:22) but it is not going to be installed or
                            esl-erlang (< 1:22) but it is not installable
                   Depends: erlang-crypto (< 1:22) but 1:22.0-1 is to be installed or
                            esl-erlang (< 1:22) but it is not installable
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This was previously posted to the [Erlang 22 compatibility announcement thread](https://groups.google.com/d/msg/rabbitmq-users/vcRLhpUdg_o/KFEaRyZHAwAJ). Please start a new thread.

This line

```
W: Skipping acquire of configured file 'erlang-20.x/i18n/Translation-en_US' as repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' doesn't have the component 'erlang-20.x' (component misspelt in sources.list?)
```
is merely a warning (`W`), not an error. Translation files are not required for a Debian package and our packages do not provide them. It does not prevent apt from updating its package indices or installing the package.
The instructions in the guide work for me on Ubuntu 18.04, specifically this sources list:

```
deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang-21.x
deb https://dl.bintray.com/rabbitmq/debian bionic main
```

The warning mentions `erlang-20.x` but you say that you used `erlang-21.x` for component. Those do not add up, either you have multiple source files or it was copied from a later attempt.
In any case, you can [pin both repository and version for apt packages](https://www.rabbitmq.com/install-debian.html#apt-pinning) as our own docs suggest.

`erlang` installs the most recent version available, which is currently Erlang 22. RabbitMQ 3.7.14 packages were released in late March, over 1 month before Erlang 22 shipped this week (earlier than we expected). [This rabbitmq-users thread](https://groups.google.com/forum/#!searchin/rabbitmq-users/bionic%7Csort:date/rabbitmq-users/Pabuzu0jajE/d8KKe2dAAQAJ) explains your range of options until 3.7.15 is released (which [will list Erlang 22 as supported](https://github.com/rabbitmq/rabbitmq-server-release/commit/0b0d6939a925f85d85baf3b6ceddf227ae32e06f)).

**Comment by digulla** [comment]
Thank you for taking the time to explain this in this issue. I was a bit disappointed that you closed if but I understand the reasons. I'll wait for updates in the forum and will live with the warnings for now.

**Comment by thijstriemstra** [comment]
Ran into same issue.

> merely a warning (W), not an error

Sure, but it is very annoying to see this at every `apt-get update`.

**Comment by michaelklishin** [comment]
Use the "main" component (`erlang`), it won't have this warning. It will provisions Erlang 22 by default. Version pinning should still work if you want to avoid an accidental upgrade to 23 (which will be released in May 2020 the earliest).

Our team produces these packages and maintains two apt repositories (one on Bintray, another on  PackageCloud) of Erlang as a side project we started because the state of latest Erlang/OTP patch release packaging from Ericsson and Erlang Solutions leaves a lot to be desired. There's only so much time we can dedicate to Erlang packaging.

These packages are *not* required to run RabbitMQ. You are welcome to use any other apt repository that provides a [supported version](https://www.rabbitmq.com/which-erlang.html).
Or use the [package source repo](https://github.com/rabbitmq/erlang-debian-package/) and maintain a PPA that would not have this warning for any of the components (I'm not 100% sure this is possible as the hosting service can be a limiting factor here). This is open source software after all.
