### ISSUE TITLE
Questions about the Maximum Connection Number of Web-stomp

### ISSUE THREAD

**Issue by DongYuLiu-Boss** [rabbitmq/rabbitmq-website#811]
When using front-end stomp.js to connect queues, why can rabbitmq-web-stomp plug-ins only connect 200, and the actual maximum connection is far more than 200.
What limits 200 connections and what parameters affect them? What can be done to solve this problem?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Nothing comes to mind. Do not guess, use Wireshark or similar to see why new connections are not accepted. Up to [`3.7.16`](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.16) there was a default limit of 1024 in the underlying TCP acceptor library that affected those plugins. It's been [lifted](https://github.com/rabbitmq/rabbitmq-web-stomp/issues/113) since.

Another incredibly common reason is [the maximum open file handle limit](https://www.rabbitmq.com/networking.html#open-file-handle-limit). It is 1024 by default on Linux, so 200 is quite a bit lower than that.

**Comment by DongYuLiu-Boss** [comment]
Thank you, my friend
