### ISSUE TITLE
 Call to undefined method

### ISSUE THREAD

**Issue by middleftw** [rabbitmq/rabbitmq-website#833]
I tried following the first tutorial (Hello World) in php.
I copy pasted the code and I get the following error in the console: 
` [*] Waiting for messages. To exit press CTRL+C
PHP Fatal error:  Uncaught Error: Call to undefined method PhpAmqpLib\Channel\AM
QPChannel::is_consuming()`

I've searched everywhere, no one seems to get this error.How can I solve this?
Thanks.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
You may be using an older version of the client (or a newer one, @lukebakken has done some releases recent but I believe the tutorials are up-to-date). Or you might have missed the dependency installation step with Composer.

See [rabbitmq/rabbitmq-tutorials](https://github.com/rabbitmq/rabbitmq-tutorials/) for an executable version.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-tutorials/pull/227 upgraded the tutorials to use the latest API.
