### ISSUE TITLE
Question ,Documentation  ,upgrade instructions for RabbitMq on windows

### ISSUE THREAD

**Issue by mrafea-sa** [rabbitmq/rabbitmq-website#849]
please provide a step by step upgrade instructions for RabbitMq on windows.
When running  rabbitmq-server-3.7.18 to upgrade  3.7.15 version,
the setup  pop an error :
{
rabbitmq already installed ,click 'ok' to remove the previous version
}
The pages on rabbitmq website  provide too many  precautions  to take care ,but does not provide direct upgrade information.
Thank you for using RabbitMQ.

**STOP NOW AND READ THIS** BEFORE OPENING A NEW ISSUE ON GITHUB

Unless you are CERTAIN you have found a reproducible problem in RabbitMQ or
have a **specific, actionable** suggestion for our team, you must first ask
your question or discuss your suspected issue on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

Team RabbitMQ does not use GitHub issues for discussions, investigations, root
cause analysis and so on.

Please take the time to read the CONTRIBUTING.md document for instructions on
how to effectively ask a question or report a suspected issue:

https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues

Following these rules **will save time** for both you and RabbitMQ's maintainers.

Thank you.

**Comment by michaelklishin** [comment]
I believe the [Upgrade guide](https://www.rabbitmq.com/upgrade.html) has a reasonable amount of specificity.

Upgrading distributed systems is very different from upgrading an app on your phone or a piece of desktop software. Single node upgrades on Windows are usually "see release notes and unless suggested otherwise, install the new package". With clusters, it is much more involved, and the docs try to be extra clear on that.

**Comment by michaelklishin** [comment]
Since most upgrade failures are system-specific, we ask the community to use [the mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users). Issues that we see repeatedly on the list will be considered for future changes both to the docs and RabbitMQ.

Contributions to the upgrade guide would also be considered, Windows-specific or not. See README of this repo to learn how to contribute.
