### ISSUE TITLE
Restart RAM node without disc node in RabbitMQ

### ISSUE THREAD

**Issue by yaboong** [rabbitmq/rabbitmq-website#936]
In RabbitMQ document, [Restarting Cluster Nodes](https://www.rabbitmq.com/clustering.html#restarting), it says

> A stopping node picks an online cluster member (only disc nodes will be considered) to sync with after restart. Upon restart the node will try to contact that peer 10 times by default, with 30 second response timeouts. In case the peer becomes available in that time interval, the node successfully starts, syncs what it needs from the peer and keeps going. If the peer does not become available, the restarted node will give up and voluntarily stop.

I think it says **"You cannot stop and restart a RAM node if there are no available disk nodes in the cluster"**.

This is because restarting the RAM node requires one or more disk nodes to sync. If there are no disk nodes in the cluster, you cannot sync the RAM nodes, so it gives up and voluntarily stops. (That's what the document says)

But the result I tried was different from what the document says. Suppose that there are three nodes in the cluster. One disk node and two RAM nodes. Let's say each node is 'disk1', 'ram1' and 'ram2'.

I thought the process would look like this:

1. `stop ram1`
2. `stop disk1` -- at this point the cluster is RAM only cluster. ('ram2' node is the only node that's alive)
3. `start ram1` -- it should not be able to start because there're no disk nodes to sync.

But the result was different than I thought. **I was able to start the RAM node on the RAM only cluster without any disk nodes.**

Did I misunderstand something?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I haven't tried it in years but such orphan RAM node would be able to start and have nowhere to sync tables from. Would you consider this a successful outcome or a safe operational scenario? I don't think so. 

RAM nodes are not necessary for 99% of use cases and with a future schema data store in 4.0 or so will go away completely. So don't build your system around them.
