### ISSUE TITLE
Suggestions on section Connecting to Clusters from Clients

### ISSUE THREAD

**Issue by oneoneonepig** [rabbitmq/rabbitmq-website#950]
According to the docs [Connecting to Clusters from Clients](https://github.com/rabbitmq/rabbitmq-website/blob/live/site/clustering.md#clients), 

> Instead, we recommend a more abstracted approach: this could be a dynamic DNS service which has a very short TTL configuration, or a plain TCP load balancer, or some sort of mobile IP achieved with pacemaker or similar technologies.

IMO, using dynamic DNS service is not that appropriate. It is one of the easiest way to achieve load balancing, but it does not have the power to react to node failure. In most of the infrastructure architectures, "service failure" does not relate to "dns updates", except for like shutting down a whole node in a cloud platform or in Kubernetes. 

I suggest that we could elaborate on the DNS part by adding more details, also adding some examples (or links) on how to achieve it.

I understand that you mentioned that it is out of scope, but it is undoubtedly one of the most important component on building a reliable RabbitMQ service.

**Comment by michaelklishin** [comment]
The section does list several alternatives. They are all valid. There are too many variables and deployment scenarios so claiming that some are "not appropriate" is arrogant. Even using a hardcoded list of endpoints can be fine or the only realistic approach in some cases. That's why the docs say *recommend* and not *require*.

Documenting DNS and load balancers is out of scope of RabbitMQ documentation guides. We already have guides that cover TLS basics, troubleshooting of networking and other general topics.

You are also missing that this section talks about *client connections* and many client libraries support lists of hosts, or (such as at least Java one) resolve hostnames to multiple addresses, and then try them all in sequence.

**Comment by oneoneonepig** [comment]
I would like to share my story with you. My current target is to provide two on-premise machines dedicated for RabbitMQ cluster, with the least probability to break the cluster down in any situation while keeping the infrastructure simple. In terms of providing reliable service, one of the approach is to declare multiple endpoints in the program, like what you mentioned in the last part, and just like many other databases with the keyword of "cluster/quorum/distributed" do.

Since I'm providing the infrastructure and service, it could be never better if there is another solution that only provides 1 single endpoint for the program to make a connection, extracting the connection logic written in the program. As what I understand, the two recommended approaches can both provided load balancing, while only TCP load balancer can provide failover (of course we can achieve anything with some fancy programming, but let's keep those components do their native work). That's the reason I'm making suggestions on elaborating the DNS part. 

I apologized for some strong words if that makes the doc owners/maintainers feel offended, I'm not a native speaker so some words might not feel the same for me and you. But I believe we are having the same goal, making a wonder documentation for RabbitMQ and let users having a great time finding what they want in this amazing place fast and accurate.

Cheers
