### ISSUE TITLE
Trying to make Memory Usage section make more sense

### ISSUE THREAD

**Issue by BentCoder** [rabbitmq/rabbitmq-website#968]
Hi,

The [Memory Usage](https://www.rabbitmq.com/channels.html#memory-use) section has confused a lot of us at work so just trying to make the explanation more sense.

> To find out how much memory on a node is used by channels, use rabbitmq-diagnostics memory_breakdown:

```bash
# => connection_channels: 3.596 mb (2.27%)
```

Does `3.596 mb` represent all active/open channels or an individual one?

For instance/testing purposes I am publishing `2000` messages in a loop which is an intense operation. For each publish I open and close a channel on purpose. The result is shown below. Does that mean my system only consumes `0.0219 mb (0.02%)` for all currently active/open channels or just one at a time? Or Am I actually looking at the wrong place?

Thanks

```bash
allocated_unused: 31.6314 mb (23.3%)
code: 30.1752 mb (22.22%)
other_proc: 24.6923 mb (18.19%)
other_system: 23.9947 mb (17.67%)
plugins: 12.1899 mb (8.98%)
mgmt_db: 6.467 mb (4.76%)
other_ets: 2.9154 mb (2.15%)
atom: 1.5177 mb (1.12%)
binary: 1.324 mb (0.98%)
metrics: 0.3868 mb (0.28%)
connection_other: 0.1771 mb (0.13%)
mnesia: 0.0802 mb (0.06%)
queue_procs: 0.0552 mb (0.04%)
connection_readers: 0.0517 mb (0.04%)
quorum_ets: 0.0474 mb (0.03%)
msg_index: 0.0297 mb (0.02%)
connection_writers: 0.0246 mb (0.02%)
connection_channels: 0.0219 mb (0.02%)
queue_slave_procs: 0.0 mb (0.0%)
quorum_queue_procs: 0.0 mb (0.0%)
reserved_unallocated: 0.0 mb (0.0%)
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
It's a category so it is the sum of memory used by channel processes (across all connections in all virtual hosts). We'd consider a PR that clarifies this. [Here's the guide in question](https://github.com/rabbitmq/rabbitmq-website/blob/live/site/memory-use.md). Thank you in advance.

**Comment by michaelklishin** [comment]
I went ahead and added a paragraph to that guide that tries to answer this very question. If you have more suggestions, feel free to submit them as PRs. Thanks!

**Comment by BentCoder** [comment]
Thanks for the message and the work you have done.

> This means that the connections category is the sum of memory used by
all connection processes, the channels category is the sum of memory used by all channel
processes

This ^ makes it very obvious now.
